In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import sys
a=range(2000)
print("Size of each element in list in bytes:",sys.getsizeof(a))
print("size of whole element in list in bytes:",sys.getsizeof(a)*len(a))


Size of each element in list in bytes: 48
size of whole element in list in bytes: 96000


In [ ]:
d=np.arange(10000)
print("Size of each element in numpy:",d.itemsize)
print("size of whole element in numpy in bytes:",d.size*d.itemsize)

Size of each element in numpy: 4
size of whole element in numpy in bytes: 40000


In [ ]:
arr=np.array(33)
print(arr)

33


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [ ]:
zeros=np.zeros((5,2))
erods=np.zeros(5)
print(zeros)
print(erods)
print(zeros.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0.]
float64


In [ ]:
zeros=np.zeros((2,3))
print(zeros)
print(zeros.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [ ]:
zeros=np.zeros((3,3) , dtype=np.int64)
print("\nArray of zerros with int:\n",zeros)



Array of zerros with int:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones=np.ones(6)
print(ones)
print(ones.dtype)

[1. 1. 1. 1. 1. 1.]
float64


In [ ]:
empty=np.empty((3,2))
print(empty)
print(empty.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64


In [ ]:
identity_matrix=np.eye(4,4)
print("\n",identity_matrix)


 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)

[1. 2. 3.] float64
[1 2 3] int32


In [ ]:
a=np.array([1,2,3])
print("Before converting:",a,a.dtype)
b=a.astype('f')
print("after converting:",b,b.dtype)

Before converting: [1 2 3] int32
after converting: [1. 2. 3.] float32


In [ ]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)
b=arr1.astype(arr2.dtype)
print(b,b.dtype)

[0 1 2 3 4 5 6 7 8 9] int32
[-0.28006846  1.24087075 -0.99770154 -1.09433698 -0.51195515  0.46548549
  0.03281449 -1.4896175  -1.24434998  0.38863434] float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [ ]:
str_arr=np.array(["Hello","world","numpy"])
print(str_arr)

['Hello' 'world' 'numpy']


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
import numpy as np
arr = np.arange(12)
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape((4, 3), order='F')
print("\n", newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4,9,10], [5, 6, 7, 8,11,12]])
print(arr)
newarr = arr. reshape (3, 2, 2)
print("\n", newarr)
newarr1 = newarr.reshape(3, -1)
print("\n reshape (3,-1) \n", newarr1)

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape (3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [ ]:
original_array = np.array([[10, 20], [30, 40]])
print("Original array:\n", original_array)
flattened_array = original_array.flatten()
flattened_array[0] = 999
print("Flattened array: \n", flattened_array)
print("Original array: \n", original_array)
raveled_array = original_array.ravel()
raveled_array [1] = 888
print("Raveled array: \n", raveled_array)
print("Original array:\n", original_array)


Original array:
 [[10 20]
 [30 40]]
Flattened array: 
 [999  20  30  40]
Original array: 
 [[10 20]
 [30 40]]
Raveled array: 
 [ 10 888  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])
greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2
print("Greater than: \n", greater_than)
print("\nLess than: \n", less_than)
print("\nEqual to: \n", equal_to)
arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4])
result1= np.array_equal(arr3, arr4)
result2 = np.array_equal(arr3, arr5)
print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)

Greater than: 
 [[False  True]
 [False False]]

Less than: 
 [[ True False]
 [False  True]]

Equal to: 
 [[False False]
 [ True False]]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [ ]:
x = np.arange(10)
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[4:7]= ",x[4:7])
print("\n x[::2]= ",x[::2])
print("\n x[1::2]= ",x[1::2])

print("\n x[::-1]= ",x[::-1])
print("\n x[5::-2]= ",x[5::-2])


x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[4:7]=  [4 5 6]

 x[::2]=  [0 2 4 6 8]

 x[1::2]=  [1 3 5 7 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2]=  [5 3 1]


In [ ]:
x = np.arange(10)
print(x)
x[5] = 2
print("\n After broadcasting1",x)
x[::2] = 100
print("\n After broadcasting2",x)

[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 6 7 8 9]

 After broadcasting2 [100   1 100   3 100   2 100   7 100   9]


In [ ]:
x2 = np.array([[12, 5, 2, 4], [ 7, 6, 8, 8], [ 1, 6, 7, 7]])
print(x2[0])
print(x2[1] [2])
print(x2 [2, -1])
print(x2[0])

[12  5  2  4]
8
7
[12  5  2  4]


In [ ]:
x2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
print("x2= ",x2)
print("\n x2[:2, :3] = \n",x2[:2, :3])
print("\n x2[:3, ::2]=\n",x2[:3, ::2])
print("\n x2[::-1,::-1]= \n",x2[::-1, ::-1])

x2=  [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

 x2[:2, :3] = 
 [[12  5  2]
 [ 7  6  8]]

 x2[:3, ::2]=
 [[12  2]
 [ 7  8]
 [ 1  7]]

 x2[::-1,::-1]= 
 [[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


In [18]:
import numpy as np
a = np.arange(12). reshape (3,4)
print("a= \n",a)
b = a > 4
print("b= \n", b)
print("a[b]= \n",a[b])
a [b] = 1
print("a= \n",a)

a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28). reshape(7, 4)
print(names)
print("data= \n", data)
print("names bool= \n", names == 'Bob')
print("names == 'Bob' \n", data [names == 'Bob'])
print("names == 'Bob',2: \n", data[names== 'Bob', 2:])
print("names == 'Bob',3 \n", data[names == 'Bob', 3])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
names bool= 
 [ True False False  True False False False]
names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]
names == 'Bob',2: 
 [[ 2  3]
 [14 15]]
names == 'Bob',3 
 [ 3 15]


In [21]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Transpose using .T")
print(arr.T)
print("Transpose using the transpose() function")
print(np.transpose(arr))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transpose() function
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [22]:
arr1=np.transpose(arr, (1, 0))
print(arr1)
arr2=np.transpose(arr, (0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print("Dot product of arr and arr2:")
print(np.dot(arr, arr.T))


Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [24]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Swap axes 0 and 1:")
print(np.swapaxes (arr, 0, 1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [28]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.multiply(arr1, arr2)
print("Result of element-wise multiplication:")
print(result)
result = np.matmul (arr1, arr2)
print("Result of matrix multiplication:")
print(result)

Result of element-wise multiplication:
[[ 5 12]
 [21 32]]
Result of matrix multiplication:
[[19 22]
 [43 50]]


In [29]:
result = np.dot (arr1, arr2)
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[19 22]
 [43 50]]
